//auth
export const auth = {
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
};
//invoice
export const invoice = {
  FETCH_INVOICE: 'FETCH_INVOICE',
  SEARCH_INVOICE: 'SEARCH_INVOICE',
  FETCH_INVOICE_CHART: 'FETCH_INVOICE_CHART',
  FETCH_SUCCESS_RATE: 'FETCH_SUCCESS_RATE',
  FETCH_ONCHANGE_INVOICE_CHART: 'FETCH_ONCHANGE_INVOICE_CHART',
  FETCH_ONCHANGE_INVOICE_CHART_SUCCESS: 'FETCH_ONCHANGE_INVOICE_CHART_SUCCESS',
  FETCH_CHART_INFO_SALDO: 'FETCH_CHART_INFO_SALDO',
  FETCHING_CHART_INFO_SALDO: 'FETCHING_CHART_INFO_SALDO',
  FETCH_TABLE_INFOSALDO: 'FETCH_TABLE_INFOSALDO',
};

export const usage = {
  FETCH_ONCHANGE_USAGE_CHART: 'FETCH_ONCHANGE_USAGE_CHART',
  FETCH_ONCHANGE_USAGE_CHART_SUCCES: 'FETCH_ONCHANGE_USAGE_CHART_SUCCES',
  FETCH_USAGE_CHART: 'FETCH_USAGE_CHART',
  FETCH_USAGE: 'FETCH_USAGE',
  SEARCH_USAGE: 'SEARCH_USAGE',
  FETCH_TABLE_USAGE: 'FETCH_TABLE_USAGE',
};
